name: appointement_phone_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.9+2
  intl_phone_field: ^3.2.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  url_launcher: ^6.3.1
  cloud_firestore: ^5.6.2
  timezone: ^0.10.0
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true


