// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Go7HNOLcwr3HT4eLLt4frHoFvwqL9oM',
    appId: '1:712163739879:web:854ea6aa3c01683b69ba42',
    messagingSenderId: '712163739879',
    projectId: 'appointment-ed3bc',
    authDomain: 'appointment-ed3bc.firebaseapp.com',
    storageBucket: 'appointment-ed3bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYmmUxMMyyT8TqPw01VhYZUn9UuKhbJAA',
    appId: '1:712163739879:android:f14dfa4ffcb4672169ba42',
    messagingSenderId: '712163739879',
    projectId: 'appointment-ed3bc',
    storageBucket: 'appointment-ed3bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpaN6irSni0_ASnRhNSQJa326oqB3GSak',
    appId: '1:712163739879:ios:693f3b98a9883f8c69ba42',
    messagingSenderId: '712163739879',
    projectId: 'appointment-ed3bc',
    storageBucket: 'appointment-ed3bc.firebasestorage.app',
    iosBundleId: 'com.example.appointementPhoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpaN6irSni0_ASnRhNSQJa326oqB3GSak',
    appId: '1:712163739879:ios:693f3b98a9883f8c69ba42',
    messagingSenderId: '712163739879',
    projectId: 'appointment-ed3bc',
    storageBucket: 'appointment-ed3bc.firebasestorage.app',
    iosBundleId: 'com.example.appointementPhoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Go7HNOLcwr3HT4eLLt4frHoFvwqL9oM',
    appId: '1:712163739879:web:1a2dd6bb79d5ed5969ba42',
    messagingSenderId: '712163739879',
    projectId: 'appointment-ed3bc',
    authDomain: 'appointment-ed3bc.firebaseapp.com',
    storageBucket: 'appointment-ed3bc.firebasestorage.app',
  );
}
