// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcvU-zJY_fqdqrRjNS4riXJ9KgwpBf2JU',
    appId: '1:807669941804:web:b431d4473a2f24d17c7389',
    messagingSenderId: '807669941804',
    projectId: 'appoint-cf2f7',
    authDomain: 'appoint-cf2f7.firebaseapp.com',
    storageBucket: 'appoint-cf2f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADgEeoTKISuhxH0QWM4nrmEksghK4F3dU',
    appId: '1:807669941804:android:0f81f259874e4a3f7c7389',
    messagingSenderId: '807669941804',
    projectId: 'appoint-cf2f7',
    storageBucket: 'appoint-cf2f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjUea68YFMVcMLNNEp8wmpxiwLH3Tq7Us',
    appId: '1:807669941804:ios:cafbf71d0e7858bf7c7389',
    messagingSenderId: '807669941804',
    projectId: 'appoint-cf2f7',
    storageBucket: 'appoint-cf2f7.firebasestorage.app',
    iosBundleId: 'com.example.appointementPhoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjUea68YFMVcMLNNEp8wmpxiwLH3Tq7Us',
    appId: '1:807669941804:ios:cafbf71d0e7858bf7c7389',
    messagingSenderId: '807669941804',
    projectId: 'appoint-cf2f7',
    storageBucket: 'appoint-cf2f7.firebasestorage.app',
    iosBundleId: 'com.example.appointementPhoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcvU-zJY_fqdqrRjNS4riXJ9KgwpBf2JU',
    appId: '1:807669941804:web:706414b6b2ec19387c7389',
    messagingSenderId: '807669941804',
    projectId: 'appoint-cf2f7',
    authDomain: 'appoint-cf2f7.firebaseapp.com',
    storageBucket: 'appoint-cf2f7.firebasestorage.app',
  );

}